# Generated by Django 5.1 on 2024-08-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_anonymousfeedback_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousfeedback',
            name='rating',
            field=models.CharField(choices=[('awesome', 'Awesome'), ('average', 'Average'), ('horrible', 'Horrible')], max_length=255, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='anonymousfeedback',
            name='review',
            field=models.TextField(verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('awesome', 'Awesome'), ('average', 'Average'), ('horrible', 'Horrible')], max_length=255, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='review',
            field=models.TextField(verbose_name='Review'),
        ),
    ]
